name: Preprocessing Automation

on:
  push:
    paths:
      - 'preprocessing/automate_Bintang-Cahya-Anwar.py'
      - 'diabetes-prediction_raw/diabetes-prediction.csv'
  workflow_dispatch:

jobs:
  preprocessing_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run automate script
        run: python preprocessing/automate_Bintang-Cahya-Anwar.py
